### ISSUE TITLE
Not an issue, just an idea

### ISSUE THREAD

**Issue by TheDeibo** [LegendOfMCPE/ClearLagg#7]
Its a issue until its been said....

to start, the plugin looks like its only for entitles... so my idea is, if you make the plugin in /help work,
it will help the user.
for example, when i used it, i only thought it was for only getting rid of entitles ( witch was still useful ) but i only just found out its possible to use it to get rid of mobs too.

if its explained on the plugin or on the discriptions  ( github and pm ) it would be easyer.
sorry for the annoyingment ( if thats a word, ) 
TheDeibo

**Comment by LDX-MCPE** [comment]
Technically, mobs are entities...

**Comment by PEMapModder** [comment]
There is `/clearlagg killmob`

**Comment by LDX-MCPE** [comment]
That's not what he was asking. He wants to know why we didn't document the killmobs functionality.

**Comment by thedeibo** [comment]
Ok... Sorry if it looks like in being rude.... I'm just giving a idea ( or making a small point )

**Comment by RocoWayne** [comment]
can you add a timer? Because use another plugin to execute the command is load more things or our servers
