### ISSUE TITLE
Doesnt clear block drops

### ISSUE THREAD

**Issue by FaZeFantasy** [LegendOfMCPE/ClearLagg#8]
Well i recently downloaded this plugin and this issue just recently came up and everytime i do /lagg clear it says "(number of entities) have been removed" but its basically still there but you cant pick it up idk if its a coding error or what not

**Comment by TonyDroidd** [comment]
It works perfect for me.

**Comment by FaZeFantasy** [comment]
it literally just started today or yesterday

**Comment by TonyDroidd** [comment]
maybe is for the lag in your server

**Comment by FaZeFantasy** [comment]
idk if its laggy it doenst lag but you never know

**Comment by Sandertv** [comment]
This is a visual bug only, and can not be resolved by this plugin.
